# Generated by Django 6.0.6 on 2026-07-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('tenant_id', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp', 'id'],
                'indexes': [models.Index(fields=['tenant_id', 'timestamp', 'id'], name='events_even_tenant__df0613_idx'), models.Index(fields=['tenant_id', 'source', 'timestamp'], name='events_even_tenant__95e4b1_idx'), models.Index(fields=['tenant_id', 'event_type', 'timestamp'], name='events_even_tenant__119f2b_idx')],
            },
        ),
    ]
