# Generated by Django 6.0.6 on 2026-07-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255)),
                ('bucket_start', models.DateTimeField()),
                ('bucket_size', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], max_length=10)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bucket_start', 'id'],
                'indexes': [models.Index(fields=['tenant_id', 'bucket_size', 'bucket_start'], name='events_even_tenant__dda975_idx'), models.Index(fields=['tenant_id', 'bucket_size', 'source', 'bucket_start'], name='events_even_tenant__6920a6_idx'), models.Index(fields=['tenant_id', 'bucket_size', 'event_type', 'bucket_start'], name='events_even_tenant__762c05_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'bucket_start', 'bucket_size', 'source', 'event_type'), name='unique_event_aggregate_bucket')],
            },
        ),
    ]
