# Generated by Django 6.0.6 on 2026-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventaggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_size', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], max_length=10, unique=True)),
                ('last_processed_until', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
